### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by playdasegunda** [YadongChen-1016/Music-Source-Separation-master#1]
We look forward to this release,

Just one question,

1. What is this "IRM oracle" I noticed that it has a very high SDR, could you tell me what it is? Thank you very much.

2. And an observation, the Demucs informed in this table, would be the Demucs V3?

**Comment by YadongChen-1016** [comment]
Thank you for your attention to this work.
1. Ideal Ratio Mask oracle (IRM), which computes the best possible mask using the ground truth sources and is the top line of the spectrogram-based method. 
2. The results of Demucs we published are from [V2,](https://arxiv.org/pdf/1911.13254v2.pdf) and the number of parameters comes from this [paper](https://arxiv.org/pdf/1909.05746v4.pdf).

**Comment by YadongChen-1016** [comment]
> We look forward to this release,
> 
> Just one question,
> 
> 1. What is this "IRM oracle" I noticed that it has a very high SDR, could you tell me what it is? Thank you very much.
> 2. And an observation, the Demucs informed in this table, would be the Demucs V3?

Thank you for your attention to this work.

Ideal Ratio Mask oracle (IRM), which computes the best possible mask using the ground truth sources and is the top line of the spectrogram-based method.
The results of Demucs we published are from [V2,](https://arxiv.org/pdf/1911.13254v2.pdf) and the number of parameters comes from this [paper](https://arxiv.org/pdf/1909.05746v4.pdf).

**Comment by YadongChen-1016** [comment]
> We look forward to this release,
> 
> Just one question,
> 
> 1. What is this "IRM oracle" I noticed that it has a very high SDR, could you tell me what it is? Thank you very much.
> 2. And an observation, the Demucs informed in this table, would be the Demucs V3?

Thank you for your attention to this work.

1. Ideal Ratio Mask oracle (IRM), which computes the best possible mask using the ground truth sources and is the top line of the spectrogram-based method.
2. The results of Demucs we published are from [V2,](https://arxiv.org/pdf/1911.13254v2.pdf) and the number of parameters comes from this [paper](https://arxiv.org/pdf/1909.05746v4.pdf).
